server:
  port: 80

spring:
  application:
    name: cloud-order-service-feign

eureka:
  client:
    register-with-eureka: false
    #是否从Eureka抓取自己的注册信息，单点无所谓。集群必须为true才能配合使用ribbon使用负载均衡
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka